CC = gcc
CXX = g++
CFLAGS = -O3 -march=native -ffast-math
CXXFLAGS = -O3 -march=native
LDLIBS =

define ENV_SH
if [ -d "$(TACO)/lib" ] && [[ ":$$LD_LIBRARY_PATH:" != *":$(TACO)/lib:"* ]]; then
  export LD_LIBRARY_PATH="$${LD_LIBRARY_PATH:+"$$LD_LIBRARY_PATH:"}$(TACO)/lib"
fi
endef
