CC = gcc-8
CXX = g++-8
CFLAGS = -ggdb# -ffast-math
CXXFLAGS = -ggdb# -ffast-math
define ENV_SH
if [ -d "$(TACO)/lib" ] && [[ ":$$LD_LIBRARY_PATH:" != *":$(TACO)/lib:"* ]]; then
  export LD_LIBRARY_PATH="$${LD_LIBRARY_PATH:+"$$LD_LIBRARY_PATH:"}$(TACO)/lib"
fi
export LD_LIBRARY_PATH
endef
