CC = gcc-8
CXX = g++
CFLAGS = -g -ffast-math
CXXFLAGS = -g -ffast-math
LDLIBS =
define ENV_SH
if [ -d "$(TACO)/lib" ] && [[ ":$$LD_LIBRARY_PATH:" != *":$(TACO)/lib:"* ]]; then
  export LD_LIBRARY_PATH="$${LD_LIBRARY_PATH:+"$$LD_LIBRARY_PATH:"}$(TACO)/lib"
fi
endef
