#!/bin/bash -l

#SBATCH -N 1         #Use 2 nodes
#SBATCH -t 01:00:00
#SBATCH -p regular   #Submit to the regular 'partition'
#SBATCH -L SCRATCH   #Job requires $SCRATCH file system
#SBATCH -C knl,quad,cache   #Use KNL nodes in quad cache format (default, recommended)

module load python
python performance_matrix.py $SCRATCH/fill_estimation/knl/performance_matrix
